version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - npm install -g n
      - n latest
      - npm update -g npm
      - npm install
      - npm install -g yarn
  pre_build:
    commands:
      - yarn add -D vuepress
  build:
    commands:
      - yarn docs:build
 
artifacts:
  files:
    - '**/*'
  base-directory: 'docs/.vuepress/dist'